// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTu1xm-J-d4qfzIIDtvtBBSz7l_taM56k',
    appId: '1:39173002442:web:792151fe7ca54ed0e6d033',
    messagingSenderId: '39173002442',
    projectId: 'test-e76eb',
    authDomain: 'test-e76eb.firebaseapp.com',
    storageBucket: 'test-e76eb.firebasestorage.app',
    measurementId: 'G-91YFGD0ZYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5U52q6672nRQtgSHHqmlOvGhNao9bdqs',
    appId: '1:39173002442:android:a78e058a72972890e6d033',
    messagingSenderId: '39173002442',
    projectId: 'test-e76eb',
    storageBucket: 'test-e76eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0sgn_Q3CC5y7LNkZ0Tk8sRMbmvN9PjU',
    appId: '1:39173002442:ios:ece7482a32c7898ce6d033',
    messagingSenderId: '39173002442',
    projectId: 'test-e76eb',
    storageBucket: 'test-e76eb.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0sgn_Q3CC5y7LNkZ0Tk8sRMbmvN9PjU',
    appId: '1:39173002442:ios:ece7482a32c7898ce6d033',
    messagingSenderId: '39173002442',
    projectId: 'test-e76eb',
    storageBucket: 'test-e76eb.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTu1xm-J-d4qfzIIDtvtBBSz7l_taM56k',
    appId: '1:39173002442:web:cc9dbf16825f79b3e6d033',
    messagingSenderId: '39173002442',
    projectId: 'test-e76eb',
    authDomain: 'test-e76eb.firebaseapp.com',
    storageBucket: 'test-e76eb.firebasestorage.app',
    measurementId: 'G-NTB527P5VG',
  );
}
